name: firebase_auth_games_services
description: "Enables logging into Firebase using Android Play Games and iOS Game Center."
version: 1.1.0
homepage: https://chunkytofustudios.com
repository: https://github.com/orkun1675/firebase_auth_games_services

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  logging: ^1.2.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.chunkytofustudios.firebase_auth_games_services
        pluginClass: FirebaseAuthGamesServicesPlugin
      ios:
        pluginClass: FirebaseAuthGamesServicesPlugin
